/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashboardsProjectCard: typeof import('./components/dashboards/project-card.vue')['default']
    DashboardsWelcomeBanner: typeof import('./components/dashboards/welcome-banner.vue')['default']
    FormsValidationTextInput: typeof import('./components/forms/validation/TextInput.vue')['default']
    FormsValidationVeeValidation: typeof import('./components/forms/validation/VeeValidation.vue')['default']
    LayoutsFooter: typeof import('./components/layouts/footer/index.vue')['default']
    LayoutsHeader: typeof import('./components/layouts/header/index.vue')['default']
    LayoutsHeaderNotification: typeof import('./components/layouts/header/notification.vue')['default']
    LayoutsHeaderProfile: typeof import('./components/layouts/header/profile.vue')['default']
    LayoutsLogo: typeof import('./components/layouts/logo/index.vue')['default']
    LayoutsSidebar: typeof import('./components/layouts/sidebar/index.vue')['default']
    LayoutsSidebarNavCollapse: typeof import('./components/layouts/sidebar/nav-collapse.vue')['default']
    LayoutsSidebarNavGroup: typeof import('./components/layouts/sidebar/nav-group.vue')['default']
    LayoutsSidebarNavItem: typeof import('./components/layouts/sidebar/nav-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedBaseBreadcrumb: typeof import('./components/shared/BaseBreadcrumb.vue')['default']
    SharedCardHeader: typeof import('./components/shared/CardHeader.vue')['default']
    SharedComponentTitle: typeof import('./components/shared/ComponentTitle.vue')['default']
    SharedSvgSprite: typeof import('./components/shared/SvgSprite.vue')['default']
    SharedUiParentCard: typeof import('./components/shared/UiParentCard.vue')['default']
  }
}
