/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormsValidationTextInput: typeof import('./components/forms/validation/TextInput.vue')['default']
    FormsValidationVeeValidation: typeof import('./components/forms/validation/VeeValidation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedBaseBreadcrumb: typeof import('./components/shared/BaseBreadcrumb.vue')['default']
    SharedCardHeader: typeof import('./components/shared/CardHeader.vue')['default']
    SharedComponentTitle: typeof import('./components/shared/ComponentTitle.vue')['default']
    SharedSvgSprite: typeof import('./components/shared/SvgSprite.vue')['default']
    SharedUiParentCard: typeof import('./components/shared/UiParentCard.vue')['default']
  }
}
